//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anzuelo.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anzuelo.Web.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combos Admin.
        /// </summary>
        public static string Admin_Combos {
            get {
                return ResourceManager.GetString("Admin_Combos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Admin.
        /// </summary>
        public static string Admin_Menu {
            get {
                return ResourceManager.GetString("Admin_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos.
        /// </summary>
        public static string Admin_Pedidos {
            get {
                return ResourceManager.GetString("Admin_Pedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preparación Admin.
        /// </summary>
        public static string Admin_Preparacion {
            get {
                return ResourceManager.GetString("Admin_Preparacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos Admin.
        /// </summary>
        public static string Admin_Productos {
            get {
                return ResourceManager.GetString("Admin_Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string Admin_Usuarios {
            get {
                return ResourceManager.GetString("Admin_Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar al carrito.
        /// </summary>
        public static string Carrito_AgregarAlCarrito {
            get {
                return ResourceManager.GetString("Carrito_AgregarAlCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Carrito_Cantidad {
            get {
                return ResourceManager.GetString("Carrito_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad debe ser mayor a cero.
        /// </summary>
        public static string Carrito_CantidadInvalida {
            get {
                return ResourceManager.GetString("Carrito_CantidadInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Carrito_MsgError {
            get {
                return ResourceManager.GetString("Carrito_MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregado al carrito.
        /// </summary>
        public static string Carrito_MsgExito {
            get {
                return ResourceManager.GetString("Carrito_MsgExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar pedido.
        /// </summary>
        public static string Carrito_RegistrarPedido {
            get {
                return ResourceManager.GetString("Carrito_RegistrarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a © 2026 Sistema El Anzuelo. Creado por: Dilan Sánchez y Adrian Rojas. Todos los derechos reservados..
        /// </summary>
        public static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especialistas en ceviches, mariscos frescos y comida tradicional costarricense..
        /// </summary>
        public static string Footer_Descripcion {
            get {
                return ResourceManager.GetString("Footer_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión/Registrarse.
        /// </summary>
        public static string Login_IniciarSesionRegistrarse {
            get {
                return ResourceManager.GetString("Login_IniciarSesionRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración.
        /// </summary>
        public static string Menu_Administracion {
            get {
                return ResourceManager.GetString("Menu_Administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combos.
        /// </summary>
        public static string Menu_Combos {
            get {
                return ResourceManager.GetString("Menu_Combos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Menu_Inicio {
            get {
                return ResourceManager.GetString("Menu_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        public static string Menu_Menu {
            get {
                return ResourceManager.GetString("Menu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preparación.
        /// </summary>
        public static string Menu_Preparacion {
            get {
                return ResourceManager.GetString("Menu_Preparacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        public static string Menu_Productos {
            get {
                return ResourceManager.GetString("Menu_Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir navegación.
        /// </summary>
        public static string Nav_AbrirNavegacion {
            get {
                return ResourceManager.GetString("Nav_AbrirNavegacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string Usuario_CerrarSesion {
            get {
                return ResourceManager.GetString("Usuario_CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de usuario.
        /// </summary>
        public static string Usuario_DetalleUsuario {
            get {
                return ResourceManager.GetString("Usuario_DetalleUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de pedidos.
        /// </summary>
        public static string Usuario_HistorialPedidos {
            get {
                return ResourceManager.GetString("Usuario_HistorialPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi cuenta.
        /// </summary>
        public static string Usuario_MiCuenta {
            get {
                return ResourceManager.GetString("Usuario_MiCuenta", resourceCulture);
            }
        }
    }
}
